# Generated by Django 5.2.14 on 2026-05-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True, verbose_name='Número de Cancha')),
                ('tipo_cancha', models.CharField(choices=[('FUTBOL_5', 'Fútbol 5'), ('FUTBOL_7', 'Fútbol 7'), ('FUTBOL_11', 'Fútbol 11'), ('PADDLE', 'Paddle'), ('TENIS', 'Tenis')], max_length=20, verbose_name='Tipo de Cancha')),
                ('superficie', models.CharField(choices=[('CESPED_SINTETICO', 'Césped Sintético'), ('CESPED_NATURAL', 'Césped Natural'), ('CEMENTO', 'Cemento'), ('POLVO_LADRILLO', 'Polvo de Ladrillo')], max_length=20, verbose_name='Tipo de Superficie')),
                ('capacidad', models.PositiveIntegerField(verbose_name='Capacidad')),
                ('estado_disponibilidad', models.BooleanField(default=True, verbose_name='Disponible')),
                ('duracion_maxima_reserva', models.PositiveIntegerField(help_text='Duración máxima de reserva en minutos', verbose_name='Duración Máxima (min)')),
                ('precio_base_hora', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Base por Hora ($)')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa (baja lógica)')),
            ],
            options={
                'verbose_name': 'Cancha',
                'verbose_name_plural': 'Canchas',
                'ordering': ['numero'],
            },
        ),
    ]
