# Generated by Django 5.2.14 on 2026-05-23 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('competitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_descuento', models.CharField(choices=[('PORCENTAJE', 'Porcentaje'), ('MONTO_FIJO', 'Monto Fijo')], max_length=20, verbose_name='Tipo de Descuento')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor (% o $)')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Descuento',
                'verbose_name_plural': 'Descuentos',
            },
        ),
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(choices=[('RESERVA', 'Reserva de Cancha'), ('CLASE', 'Clase/Entrenamiento'), ('COMPETENCIA', 'Inscripción a Competencia'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de Servicio')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto ($)')),
                ('fecha_cobro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Cobro')),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA_DEBITO', 'Tarjeta de Débito'), ('TARJETA_CREDITO', 'Tarjeta de Crédito'), ('TRANSFERENCIA', 'Transferencia'), ('MERCADO_PAGO', 'Mercado Pago')], max_length=20, verbose_name='Método de Pago')),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20, verbose_name='Estado del Pago')),
                ('clase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobros', to='bookings.claseentrenamiento', verbose_name='Clase')),
                ('competencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobros', to='competitions.competencia', verbose_name='Competencia')),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobros', to='bookings.reserva', verbose_name='Reserva')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobros', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('descuento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobros', to='finance.descuento', verbose_name='Descuento')),
            ],
            options={
                'verbose_name': 'Cobro',
                'verbose_name_plural': 'Cobros',
                'ordering': ['-fecha_cobro'],
            },
        ),
        migrations.CreateModel(
            name='ReciboPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.TextField(verbose_name='Detalle')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('cobro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recibo', to='finance.cobro', verbose_name='Cobro')),
            ],
            options={
                'verbose_name': 'Recibo de Pago',
                'verbose_name_plural': 'Recibos de Pago',
            },
        ),
    ]
