"""
Django settings for gol_ahora_back project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
#agrego la importación de librerías de db
import os
import dj_database_url


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=3=(9ot(i7246gf%^isck=wvi5rwi^qo=+ep*7*-retnz25)(q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'rest_framework',
    'corsheaders',
    'django_filters',
    'drf_spectacular',
    # Apps del proyecto
    'authentication',
    'fields',
    'bookings',
    'finance',
    'competitions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS — antes de CommonMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gol_ahora_back.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gol_ahora_back.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
#
# PostgreSQL (producción) — descomentar y configurar credenciales:
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'gol_ahora',
#         'USER': 'postgres',
#         'PASSWORD': 'postgres',
#         'HOST': 'localhost',
#         'PORT': '5432',
#     }
# }

# =========================================================================
# CONFIGURACIÓN DE BASE DE DATOS INTELIGENTE (LOCAL VS PRODUCCIÓN)
# =========================================================================
if os.environ.get('DATABASE_URL'):
    # Si detecta la variable en Render, se conecta directo a Postgres en Neon
    DATABASES = {
        'default': dj_database_url.parse(os.environ.get('DATABASE_URL'))
    }
    DATABASES['default']['ENGINE'] = 'django.db.backends.postgresql'
    DATABASES['default']['CONN_MAX_AGE'] = 600
else:
    # Si tus compañeros corren el proyecto local en su PC mediante db.sqlite3
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
# =========================================================================


# Custom User Model
AUTH_USER_MODEL = 'authentication.Usuario'


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'es-ar'
TIME_ZONE = 'America/Argentina/Buenos_Aires'
USE_I18N = True
USE_TZ = True


# =========================================================================
# CONFIGURACIÓN DE SEGURIDAD CORS Y CSRF PARA REACT (CORREGIDA)
# =========================================================================
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True
#SESSION_COOKIE_SAMESITE = 'None'  # Permite cookies entre Render y Vercel
#SESSION_COOKIE_SECURE = True      # Requerido si SameSite es 'None'
#CSRF_COOKIE_SAMESITE = 'None'
#CSRF_COOKIE_SECURE = True
# 1. Permitir que Render aloje el backend de pruebas
ALLOWED_HOSTS = [
    'gol-ahora-backend-1.onrender.com',
    'gol-ahora-backend-pruebas.onrender.com',  # <-- Tu backend de pruebas
    'localhost',
    '127.0.0.1',
]

# 2. Permitir que el Frontend de Vercel de pruebas lea los datos (CORS)
CORS_ALLOWED_ORIGINS = [
    'https://gol-ahora-frontend.vercel.app',
    'https://gol-ahora-ramiro-pruebas.vercel.app',  # <-- Tu frontend de pruebas
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]

# 3. Permitir que el Frontend de pruebas mande formularios y logins (CSRF)
CSRF_TRUSTED_ORIGINS = [
    'https://gol-ahora-backend-1.onrender.com',
    'https://gol-ahora-backend-pruebas.onrender.com',
    'https://gol-ahora-frontend.vercel.app',
    'https://gol-ahora-ramiro-pruebas.vercel.app',  # <-- Confianza para pruebas
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]

# Django REST Framework — Configuración Optimizada para React
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# Swagger / Spectacular settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'Gol Ahora API',
    'DESCRIPTION': 'API endpoints para el sistema Gol Ahora',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Evita que Django rompa o mude peticiones POST/PUT si el front omite la barra final
APPEND_SLASH = False