# Generated by Django 5.2.14 on 2026-05-23 14:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('tipo_competencia', models.CharField(choices=[('LIGA', 'Liga'), ('TORNEO', 'Torneo'), ('COPA', 'Copa')], max_length=20, verbose_name='Tipo de Competencia')),
                ('fixture', models.JSONField(blank=True, default=dict, help_text='Objeto JSON flexible con la estructura del fixture', verbose_name='Fixture')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participantes', models.ManyToManyField(blank=True, related_name='competencias', to=settings.AUTH_USER_MODEL, verbose_name='Participantes')),
            ],
            options={
                'verbose_name': 'Competencia',
                'verbose_name_plural': 'Competencias',
            },
        ),
    ]
