# Generated by Django 5.2.14 on 2026-05-31 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
        ('fields', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competencia',
            options={'ordering': ['-created_at'], 'verbose_name': 'Competencia', 'verbose_name_plural': 'Competencias'},
        ),
        migrations.RemoveField(
            model_name='competencia',
            name='fixture',
        ),
        migrations.RemoveField(
            model_name='competencia',
            name='participantes',
        ),
        migrations.AddField(
            model_name='competencia',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='competencia',
            name='estado',
            field=models.CharField(choices=[('INSCRIPCION_ABIERTA', 'Inscripción Abierta'), ('INSCRIPCION_CERRADA', 'Inscripción Cerrada'), ('EN_CURSO', 'En Curso'), ('FINALIZADA', 'Finalizada')], default='INSCRIPCION_ABIERTA', max_length=25, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='competencia',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Fin'),
        ),
        migrations.AddField(
            model_name='competencia',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Inicio'),
        ),
        migrations.AddField(
            model_name='competencia',
            name='max_equipos',
            field=models.PositiveIntegerField(choices=[(8, '8 equipos'), (16, '16 equipos')], default=8, verbose_name='Máximo de Equipos'),
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre del Equipo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('capitan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_como_capitan', to=settings.AUTH_USER_MODEL, verbose_name='Capitán')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MiembroEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='competitions.equipo', verbose_name='Equipo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Miembro de Equipo',
                'verbose_name_plural': 'Miembros de Equipo',
                'unique_together': {('equipo', 'usuario')},
            },
        ),
        migrations.AddField(
            model_name='equipo',
            name='jugadores',
            field=models.ManyToManyField(blank=True, related_name='equipos', through='competitions.MiembroEquipo', to=settings.AUTH_USER_MODEL, verbose_name='Jugadores'),
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora')),
                ('ronda', models.CharField(choices=[('OCTAVOS', 'Octavos de Final'), ('CUARTOS', 'Cuartos de Final'), ('SEMIFINAL', 'Semifinal'), ('FINAL', 'Final')], max_length=15, verbose_name='Ronda')),
                ('numero_partido', models.PositiveIntegerField(verbose_name='Número de Partido')),
                ('posicion_siguiente', models.CharField(blank=True, choices=[('LOCAL', 'Local'), ('VISITANTE', 'Visitante')], max_length=10, null=True, verbose_name='Posición en Partido Siguiente')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_CURSO', 'En Curso'), ('FINALIZADO', 'Finalizado'), ('SUSPENDIDO', 'Suspendido')], default='PENDIENTE', max_length=10, verbose_name='Estado')),
                ('cancha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos', to='fields.cancha', verbose_name='Cancha')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='competitions.competencia', verbose_name='Competencia')),
                ('equipo_local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos_como_local', to='competitions.equipo', verbose_name='Equipo Local')),
                ('equipo_visitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos_como_visitante', to='competitions.equipo', verbose_name='Equipo Visitante')),
                ('partido_siguiente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos_previos', to='competitions.partido', verbose_name='Partido Siguiente (bracket)')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'ordering': ['ronda', 'numero_partido'],
                'unique_together': {('competencia', 'ronda', 'numero_partido')},
            },
        ),
        migrations.CreateModel(
            name='Reglamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('duracion_partido_min', models.PositiveIntegerField(default=60, verbose_name='Duración del Partido (min)')),
                ('jugadores_por_equipo', models.PositiveIntegerField(default=5, verbose_name='Jugadores por Equipo')),
                ('competencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reglamento', to='competitions.competencia', verbose_name='Competencia')),
            ],
            options={
                'verbose_name': 'Reglamento',
                'verbose_name_plural': 'Reglamentos',
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goles_local', models.PositiveIntegerField(default=0, verbose_name='Goles Local')),
                ('goles_visitante', models.PositiveIntegerField(default=0, verbose_name='Goles Visitante')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('equipo_ganador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos_ganados', to='competitions.equipo', verbose_name='Equipo Ganador')),
                ('partido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='competitions.partido', verbose_name='Partido')),
            ],
            options={
                'verbose_name': 'Resultado',
                'verbose_name_plural': 'Resultados',
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=10, verbose_name='Estado')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Inscripción')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='competitions.competencia', verbose_name='Competencia')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='competitions.equipo', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['-fecha_inscripcion'],
                'unique_together': {('competencia', 'equipo')},
            },
        ),
    ]
