# Generated by Django 5.2.14 on 2026-05-23 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fields', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('estado_asistencia', models.CharField(choices=[('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente'), ('JUSTIFICADO', 'Justificado')], default='AUSENTE', max_length=20, verbose_name='Estado')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to=settings.AUTH_USER_MODEL, verbose_name='Alumno')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
            },
        ),
        migrations.CreateModel(
            name='ClaseEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateTimeField(verbose_name='Horario')),
                ('maximo_alumnos', models.PositiveIntegerField(verbose_name='Máximo de Alumnos')),
                ('tipo_clase', models.CharField(choices=[('FUNCIONAL', 'Funcional'), ('FUTBOL', 'Fútbol'), ('PADDLE', 'Paddle'), ('PERSONALIZADO', 'Personalizado')], max_length=20, verbose_name='Tipo de Clase')),
                ('alumnos', models.ManyToManyField(blank=True, related_name='clases_inscriptas', through='bookings.Asistencia', to=settings.AUTH_USER_MODEL, verbose_name='Alumnos Inscriptos')),
                ('cancha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases', to='fields.cancha', verbose_name='Cancha')),
                ('profesor', models.ForeignKey(limit_choices_to={'rol': 'PROFESOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='clases_dictadas', to=settings.AUTH_USER_MODEL, verbose_name='Profesor')),
            ],
            options={
                'verbose_name': 'Clase de Entrenamiento',
                'verbose_name_plural': 'Clases de Entrenamiento',
                'ordering': ['-horario'],
            },
        ),
        migrations.AddField(
            model_name='asistencia',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='bookings.claseentrenamiento', verbose_name='Clase'),
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('clase', 'alumno')},
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(verbose_name='Fecha de Reserva')),
                ('hora_inicio', models.DateTimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.DateTimeField(verbose_name='Hora de Fin')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('antelacion_cancelacion', models.PositiveIntegerField(default=24, help_text='Horas de antelación para cancelar', verbose_name='Antelación de Cancelación (hs)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='fields.cancha', verbose_name='Cancha')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-fecha_reserva'],
                'constraints': [models.UniqueConstraint(fields=('cancha', 'fecha_reserva', 'hora_inicio'), name='unique_cancha_fecha_hora')],
            },
        ),
    ]
